language: bash

dist: focal

services:
    - docker

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
    - docker build -t mengdemao/bytebox .

after_success:
    - docker push mengdemao/bytebox:latest

deploy:
  provider: script
  script: docker push mengdemao/bytebox:latest
  on:
    tags: true
